#!/usr/bin/env python3
"""bensz-nsfc 版本管理安装器（统一框架薄封装）"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any


def _load_shared_module():
    try:
        import package_version_manager as module

        return module
    except ImportError:
        for parent in Path(__file__).resolve().parents:
            helper_dir = parent / "scripts"
            if (helper_dir / "package_version_manager.py").exists():
                sys.path.insert(0, str(helper_dir))
                import package_version_manager as module

                return module
        raise


PVM = _load_shared_module()

REPO_OWNER = "huangwb8"
REPO_NAME = "ChineseResearchLaTeX"
PACKAGE_NAME = "bensz-nsfc"
PACKAGE_DIR = Path(__file__).resolve().parents[2]
LOCKFILE_NAME = ".nsfc-version"
TEMPLATE_IDS = ("general", "local", "young")


class NSFCPackageManager(PVM.VersionedPackageManager, PVM.ProjectLockMixin):
    lockfile_name = LOCKFILE_NAME
    template_ids = TEMPLATE_IDS

    def __init__(
        self,
        *,
        cwd: Path | None = None,
        texmfhome_override: str | None = None,
    ) -> None:
        super().__init__(
            spec=PVM.PackageSpec(
                package_name=PACKAGE_NAME,
                source_marker="bensz-nsfc-common.sty",
                dependency_package_names=("bensz-fonts",),
            ),
            cwd=cwd,
            texmfhome_override=texmfhome_override,
            package_dir_override=PACKAGE_DIR,
        )
        self._migrate_legacy_state()

    def _migrate_legacy_state(self) -> None:
        state = self._state()
        previous = state.pop("previous_commit", None)
        if previous:
            history = list(state.get("history") or [])
            if previous not in history:
                history.insert(0, previous)
            state["history"] = history[:20]
            self._save_state(state)

    def after_activate(self, commit: str, dry_run: bool = False) -> None:
        if dry_run:
            return
        target = self._target_install_dir()
        runtime_file = target / "bensz-nsfc-runtime.def"
        package_root = target.resolve().as_posix() + "/"
        assets_dir = package_root + "assets/"
        fonts_package_dir = target.parent / "bensz-fonts"
        if (fonts_package_dir / "bensz-fonts.sty").exists():
            assets_fonts_dir = fonts_package_dir.resolve().as_posix() + "/fonts/"
        else:
            assets_fonts_dir = assets_dir + "fonts/"
        asset_bib_style_base = assets_dir + "bibtex-style/gbt7714-nsfc"
        runtime_file.write_text(
            "\n".join(
                [
                    "% Auto-generated by packages/bensz-nsfc/scripts/package/install.py",
                    f"\\renewcommand{{\\NSFCPackageRootDir}}{{{package_root}}}",
                    f"\\renewcommand{{\\NSFCAssetsDir}}{{{assets_dir}}}",
                    f"\\renewcommand{{\\NSFCAssetFontsDir}}{{{assets_fonts_dir}}}",
                    f"\\renewcommand{{\\NSFCAssetBibStyleBase}}{{{asset_bib_style_base}}}",
                    "",
                ]
            ),
            encoding="utf-8",
        )

    def _detect_template_id(self, project_root: Path) -> str:
        config_file = project_root / "extraTex" / "@config.tex"
        if config_file.exists():
            content = config_file.read_text(encoding="utf-8", errors="ignore")
            for template_id in self.template_ids:
                if f"type={template_id}" in content:
                    return template_id
        mapping = {
            "NSFC_General": "general",
            "NSFC_Local": "local",
            "NSFC_Young": "young",
        }
        return mapping.get(project_root.name, "general")

    def prune(self, *, dry_run: bool = False) -> dict[str, Any]:
        state = self._state()
        current = state.get("current") or {}
        keep = {item for item in [current.get("commit")] + list(state.get("history") or []) if item}
        for lockfile in self.repo_root.rglob(LOCKFILE_NAME):
            try:
                keep.add(json.loads(lockfile.read_text(encoding="utf-8")).get("commit"))
            except (json.JSONDecodeError, OSError):
                continue
        removed: list[str] = []
        if not self.cache_root.exists():
            return {"kept": sorted(keep), "removed": removed}
        for commit_dir in self.cache_root.iterdir():
            if commit_dir.name in keep:
                continue
            removed.append(commit_dir.name)
            if not dry_run:
                import shutil

                shutil.rmtree(commit_dir, ignore_errors=True)
        return {"kept": sorted(keep), "removed": sorted(removed)}

    def _fetch_json(self, url: str) -> Any:
        headers = self._github_headers()
        request = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(request) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            raise PVM.InstallError(f"请求失败：{exc.code} {url}") from exc
        except urllib.error.URLError as exc:
            raise PVM.InstallError(f"无法访问：{url}") from exc

    def _resolve_ref(self, ref: str) -> dict[str, Any]:
        cached = self._cached_ref(ref)
        if cached:
            return cached
        url = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/commits/{urllib.parse.quote(ref, safe='')}"
        payload = self._fetch_json(url)
        resolved = {
            "requested_ref": ref,
            "resolved_commit": payload["sha"],
            "commit_date": payload.get("commit", {}).get("committer", {}).get("date"),
            "source": "github",
            "resolved_at": self._timestamp(),
        }
        self._json_dump(self.refs_root / f"{self._safe_ref_name(ref)}.json", resolved)
        return resolved

    def list_remote(self) -> dict[str, Any]:
        releases = self._fetch_json(f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/releases")
        tags = self._fetch_json(f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/tags?per_page=100")
        payload = {
            "fetched_at": self._timestamp(),
            "releases": [
                {
                    "tag_name": item.get("tag_name"),
                    "published_at": item.get("published_at"),
                    "prerelease": item.get("prerelease"),
                }
                for item in releases
            ],
            "tags": [item.get("name") for item in tags],
        }
        return payload

    def info(self, ref: str) -> dict[str, Any]:
        resolved = self._resolve_ref(ref)
        cached = self._cached_ref(ref)
        return {"resolved": resolved, "cached": cached}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="NSFC 公共包安装/切换/锁定工具")
    parser.add_argument("--texmfhome", metavar="PATH")
    subparsers = parser.add_subparsers(dest="command", required=True)

    install_parser = subparsers.add_parser("install")
    install_parser.add_argument("--ref", required=True)
    install_parser.add_argument("--source", choices=("github", "release", "local"), default="github")
    install_parser.add_argument("--mirror", choices=("github", "gitee", "auto"), default="github")
    install_parser.add_argument("--path", type=Path)
    install_parser.add_argument("--force", action="store_true")
    install_parser.add_argument("--dry-run", action="store_true")
    install_parser.add_argument("--no-activate", action="store_true")

    use_parser = subparsers.add_parser("use")
    use_parser.add_argument("--ref", required=True)
    use_parser.add_argument("--dry-run", action="store_true")

    pin_parser = subparsers.add_parser("pin")
    pin_parser.add_argument("--ref")
    pin_parser.add_argument("--dry-run", action="store_true")

    sync_parser = subparsers.add_parser("sync")
    sync_parser.add_argument("--dry-run", action="store_true")

    subparsers.add_parser("check")

    rollback_parser = subparsers.add_parser("rollback")
    rollback_parser.add_argument("--dry-run", action="store_true")

    uninstall_parser = subparsers.add_parser("uninstall")
    uninstall_parser.add_argument("--dry-run", action="store_true")

    subparsers.add_parser("status")

    list_parser = subparsers.add_parser("list")
    list_parser.add_argument("--remote", action="store_true")

    info_parser = subparsers.add_parser("info")
    info_parser.add_argument("--ref", required=True)

    unpin_parser = subparsers.add_parser("unpin")
    unpin_parser.add_argument("--dry-run", action="store_true")

    prune_parser = subparsers.add_parser("prune")
    prune_parser.add_argument("--dry-run", action="store_true")

    return parser


def build_manager(args: argparse.Namespace) -> NSFCPackageManager:
    return NSFCPackageManager(
        cwd=Path.cwd(),
        texmfhome_override=getattr(args, "texmfhome", None),
    )


def main(argv: list[str] | None = None) -> int:
    PVM.configure_windows_stdio_utf8()
    parser = build_parser()
    args = parser.parse_args(argv)
    manager = build_manager(args)

    try:
        if args.command == "install":
            result = manager.install(
                ref=args.ref,
                source=args.source,
                mirror=args.mirror,
                activate=not args.no_activate,
                force=args.force,
                dry_run=args.dry_run,
                path=str(args.path) if args.path else None,
            )
        elif args.command == "use":
            result = manager.use(args.ref, dry_run=args.dry_run)
        elif args.command == "pin":
            result = manager.pin(args.ref, dry_run=args.dry_run)
        elif args.command == "sync":
            result = manager.sync(dry_run=args.dry_run)
        elif args.command == "check":
            result = manager.check()
        elif args.command == "rollback":
            result = manager.rollback(dry_run=args.dry_run)
        elif args.command == "uninstall":
            result = manager.uninstall(dry_run=args.dry_run)
        elif args.command == "status":
            result = manager.status()
        elif args.command == "list":
            if args.remote:
                result = manager.list_remote()
            else:
                result = manager.list_cached()
        elif args.command == "info":
            result = manager.info(args.ref)
        elif args.command == "unpin":
            result = manager.unpin(dry_run=args.dry_run)
        elif args.command == "prune":
            result = manager.prune(dry_run=args.dry_run)
        else:
            raise PVM.InstallError(f"不支持的命令：{args.command}")
    except PVM.InstallError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(json.dumps(result, ensure_ascii=False, indent=2))
    if args.command == "check":
        return 0 if result.get("status") in {"match", "unlocked"} else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
