#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from contextlib import contextmanager
from pathlib import Path

PACKAGE_DIR = Path(__file__).resolve().parents[1]


def parse_provides_package(style_file: Path) -> tuple[str, str]:
    content = style_file.read_text(encoding="utf-8")
    match = re.search(
        r"\\ProvidesPackage\{bensz-nsfc-common\}\[(\d{4}/\d{2}/\d{2})\s+([^\s]+)",
        content,
    )
    if not match:
        raise ValueError(f"无法解析 {style_file} 中的 ProvidesPackage")
    return match.group(1), match.group(2)


def validate_required_files() -> list[str]:
    required = [
        "bensz-nsfc-common.sty",
        "bensz-nsfc-core.sty",
        "bensz-nsfc-layout.sty",
        "bensz-nsfc-typography.sty",
        "bensz-nsfc-headings.sty",
        "bensz-nsfc-bibliography.sty",
        "assets/fonts/Kaiti.ttf",
        "assets/fonts/SimSun.ttf",
        "assets/fonts/TimesNewRoman.ttf",
        "assets/bibtex-style/gbt7714-nsfc.bst",
        "profiles/bensz-nsfc-profile-general.def",
        "profiles/bensz-nsfc-profile-local.def",
        "profiles/bensz-nsfc-profile-young.def",
        "package.json",
        "README.md",
        "examples/basic-usage.tex",
        "examples/basic-bibliography.tex",
        "examples/example.bib",
    ]
    missing = [entry for entry in required if not (PACKAGE_DIR / entry).exists()]
    return missing


def _compile_command(command: list[str], cwd: Path, env: dict[str, str]) -> tuple[int, str]:
    result = subprocess.run(
        command,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
        env=env,
    )
    return result.returncode, result.stdout[-4000:]


def _write_runtime_file(package_dir: Path) -> None:
    package_root = package_dir.resolve().as_posix() + "/"
    assets_dir = package_root + "assets/"
    assets_fonts_dir = assets_dir + "fonts/"
    asset_bib_style_base = assets_dir + "bibtex-style/gbt7714-nsfc"
    (package_dir / "bensz-nsfc-runtime.def").write_text(
        "\n".join(
            [
                "% Auto-generated by packages/bensz-nsfc/scripts/validate_package.py",
                f"\\renewcommand{{\\NSFCPackageRootDir}}{{{package_root}}}",
                f"\\renewcommand{{\\NSFCAssetsDir}}{{{assets_dir}}}",
                f"\\renewcommand{{\\NSFCAssetFontsDir}}{{{assets_fonts_dir}}}",
                f"\\renewcommand{{\\NSFCAssetBibStyleBase}}{{{asset_bib_style_base}}}",
                "",
            ]
        ),
        encoding="utf-8",
    )


@contextmanager
def _package_copy() -> Path:
    with tempfile.TemporaryDirectory(prefix="bensz-nsfc-validate-") as temp_dir:
        temp_package_dir = Path(temp_dir) / "bensz-nsfc"
        shutil.copytree(PACKAGE_DIR, temp_package_dir)
        _write_runtime_file(temp_package_dir)
        yield temp_package_dir


def _example_env(package_dir: Path) -> dict[str, str]:
    env = dict(**os.environ)
    texinputs = str(package_dir) + "//" + os.pathsep
    if env.get("TEXINPUTS"):
        texinputs = texinputs + env["TEXINPUTS"]
    env["TEXINPUTS"] = texinputs
    return env


def compile_example() -> dict[str, str | int]:
    with _package_copy() as package_dir:
        example_dir = package_dir / "examples"
        env = _example_env(package_dir)
        returncode, stdout = _compile_command(
            ["xelatex", "-interaction=nonstopmode", "-halt-on-error", "basic-usage.tex"],
            cwd=example_dir,
            env=env,
        )
        return {"returncode": returncode, "stdout": stdout}


def compile_bibliography_example() -> dict[str, str | int]:
    with _package_copy() as package_dir:
        example_dir = package_dir / "examples"
        env = _example_env(package_dir)
        steps = [
            ["xelatex", "-interaction=nonstopmode", "-halt-on-error", "basic-bibliography.tex"],
            ["bibtex", "basic-bibliography"],
            ["xelatex", "-interaction=nonstopmode", "-halt-on-error", "basic-bibliography.tex"],
            ["xelatex", "-interaction=nonstopmode", "-halt-on-error", "basic-bibliography.tex"],
        ]
        last_stdout = ""
        for command in steps:
            returncode, stdout = _compile_command(command, cwd=example_dir, env=env)
            last_stdout = stdout
            if returncode != 0:
                return {"returncode": returncode, "stdout": stdout, "failed_command": " ".join(command)}
        return {"returncode": 0, "stdout": last_stdout}


def main() -> int:
    parser = argparse.ArgumentParser(description="校验 bensz-nsfc 公共包")
    parser.add_argument("--skip-compile", action="store_true")
    args = parser.parse_args()

    missing = validate_required_files()
    if missing:
        print(json.dumps({"status": "error", "missing_files": missing}, ensure_ascii=False, indent=2))
        return 1

    package_json = json.loads((PACKAGE_DIR / "package.json").read_text(encoding="utf-8"))
    _, style_version = parse_provides_package(PACKAGE_DIR / "bensz-nsfc-common.sty")
    status = {
        "status": "ok",
        "package_version": package_json["version"],
        "style_version": style_version,
        "templates": package_json.get("templates", {}),
    }
    if package_json["version"] != style_version:
        status["status"] = "error"
        status["reason"] = "package.json.version 与 ProvidesPackage 版本不一致"
        print(json.dumps(status, ensure_ascii=False, indent=2))
        return 1

    if not args.skip_compile:
        compile_result = compile_example()
        status["example_compile"] = compile_result
        if compile_result["returncode"] != 0:
            status["status"] = "error"
            print(json.dumps(status, ensure_ascii=False, indent=2))
            return 1
        bibliography_compile_result = compile_bibliography_example()
        status["bibliography_example_compile"] = bibliography_compile_result
        if bibliography_compile_result["returncode"] != 0:
            status["status"] = "error"
            print(json.dumps(status, ensure_ascii=False, indent=2))
            return 1

    print(json.dumps(status, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
