#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = REPO_ROOT / "packages" / "bensz-nsfc"
PROJECT_ROOT_MARKERS = ("main.tex", "extraTex/@config.tex")
CACHE_DIRNAME = ".latex-cache"
ROOT_ARTIFACT_PATTERNS = (
    "*.aux",
    "*.log",
    "*.out",
    "*.toc",
    "*.lof",
    "*.lot",
    "*.bbl",
    "*.blg",
    "*.fls",
    "*.fdb_latexmk",
    "*.bcf",
    "*.run.xml",
    "*.nav",
    "*.snm",
    "*.vrb",
    "*.synctex.gz",
    "*.synctex(busy)",
    "*.dvi",
    "*.xdv",
)
TOOL_CANDIDATES = {
    "xelatex": (
        "/Library/TeX/texbin/xelatex",
        "/usr/local/texlive/2024/bin/universal-darwin/xelatex",
        "/usr/local/texlive/2024/bin/x86_64-linux/xelatex",
    ),
    "bibtex": (
        "/Library/TeX/texbin/bibtex",
        "/usr/local/texlive/2024/bin/universal-darwin/bibtex",
        "/usr/local/texlive/2024/bin/x86_64-linux/bibtex",
    ),
}


class BuildError(RuntimeError):
    pass


def is_project_root(path: Path) -> bool:
    return all((path / marker).exists() for marker in PROJECT_ROOT_MARKERS)


def find_project_root(start: Path | None = None) -> Path:
    origin = (start or Path.cwd()).expanduser().resolve()
    for candidate in [origin, *origin.parents]:
        if is_project_root(candidate):
            return candidate
    raise FileNotFoundError(
        "无法定位 NSFC 项目根目录。请在项目目录内运行，或使用 --project-dir 显式指定。"
    )


def resolve_project_dir(project_dir: Path | None) -> Path:
    if project_dir is None:
        return find_project_root()
    candidate = project_dir.expanduser().resolve()
    if not candidate.exists():
        raise FileNotFoundError(f"项目目录不存在：{candidate}")
    if candidate.is_file():
        candidate = candidate.parent
    if is_project_root(candidate):
        return candidate
    return find_project_root(candidate)


def resolve_tex_file(project_dir: Path, tex_file: str) -> Path:
    candidate = (project_dir / tex_file).resolve()
    if not candidate.exists():
        raise FileNotFoundError(f"TeX 主文件不存在：{candidate}")
    if candidate.parent != project_dir:
        raise BuildError("当前渲染器仅支持项目根目录下的主 TeX 文件。")
    return candidate


def resolve_executable(name: str) -> str:
    resolved = shutil.which(name)
    if resolved:
        return resolved
    for candidate in TOOL_CANDIDATES.get(name, ()):
        if Path(candidate).exists():
            return candidate
    raise FileNotFoundError(f"未找到可执行文件：{name}")


def build_texinputs(prefixes: list[Path], existing: str) -> str:
    normalized = [f"{path.resolve()}//" for path in prefixes]
    normalized.append("")
    if existing:
        normalized.append(existing)
    return os.pathsep.join(normalized)


def write_runtime_file(cache_dir: Path) -> Path:
    runtime_path = cache_dir / "bensz-nsfc-runtime.def"
    package_root = PACKAGE_DIR.resolve().as_posix() + "/"
    assets_dir = package_root + "assets/"
    assets_fonts_dir = assets_dir + "fonts/"
    asset_bib_style_base = assets_dir + "bibtex-style/gbt7714-nsfc"
    runtime_path.write_text(
        "\n".join(
            [
                "% Auto-generated by scripts/nsfc_project_tool.py. Do not edit manually.",
                f"\\renewcommand{{\\NSFCPackageRootDir}}{{{package_root}}}",
                f"\\renewcommand{{\\NSFCAssetsDir}}{{{assets_dir}}}",
                f"\\renewcommand{{\\NSFCAssetFontsDir}}{{{assets_fonts_dir}}}",
                f"\\renewcommand{{\\NSFCAssetBibStyleBase}}{{{asset_bib_style_base}}}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return runtime_path


def sync_reference_inputs(cache_dir: Path, project_dir: Path) -> None:
    source = project_dir / "references"
    target = cache_dir / "references"
    if target.exists() or target.is_symlink():
        if target.is_symlink() or target.is_file():
            target.unlink()
        else:
            shutil.rmtree(target)
    try:
        relative_source = Path("..") / "references"
        target.symlink_to(relative_source, target_is_directory=True)
    except OSError:
        shutil.copytree(source, target)


def clean_root_artifacts(project_dir: Path, tex_stem: str) -> None:
    for pattern in ROOT_ARTIFACT_PATTERNS:
        for path in project_dir.glob(pattern):
            if path.name == f"{tex_stem}.pdf":
                continue
            if path.is_file() or path.is_symlink():
                path.unlink(missing_ok=True)


def summarize_process_output(label: str, result: subprocess.CompletedProcess[str]) -> str:
    lines = [line for line in (result.stdout + "\n" + result.stderr).splitlines() if line.strip()]
    tail = "\n".join(lines[-30:]) if lines else "(no output)"
    return f"[{label}] exit={result.returncode}\n{tail}"


def run_best_effort(
    args: list[str],
    *,
    cwd: Path,
    env: dict[str, str],
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        cwd=cwd,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )


def build_project(project_dir: Path, tex_file: str) -> None:
    tex_path = resolve_tex_file(project_dir, tex_file)
    tex_stem = tex_path.stem
    cache_dir = project_dir / CACHE_DIRNAME
    cache_dir.mkdir(parents=True, exist_ok=True)

    write_runtime_file(cache_dir)
    sync_reference_inputs(cache_dir, project_dir)
    clean_root_artifacts(project_dir, tex_stem)

    tex_env = os.environ.copy()
    tex_env["TEXINPUTS"] = build_texinputs([cache_dir, PACKAGE_DIR], tex_env.get("TEXINPUTS", ""))

    xelatex_bin = resolve_executable("xelatex")
    bibtex_bin = resolve_executable("bibtex")

    xelatex_cmd = [
        xelatex_bin,
        "-interaction=nonstopmode",
        "-file-line-error",
        "-synctex=1",
        f"-output-directory={cache_dir}",
        tex_path.name,
    ]
    bibtex_cmd = [bibtex_bin, tex_stem]

    xelatex_run_1 = run_best_effort(xelatex_cmd, cwd=project_dir, env=tex_env)
    bibtex_run = run_best_effort(bibtex_cmd, cwd=cache_dir, env=tex_env)
    xelatex_run_2 = run_best_effort(xelatex_cmd, cwd=project_dir, env=tex_env)
    xelatex_run_3 = run_best_effort(xelatex_cmd, cwd=project_dir, env=tex_env)

    pdf_source = cache_dir / f"{tex_stem}.pdf"
    if not pdf_source.exists():
        compiler_logs = "\n\n".join(
            [
                summarize_process_output("xelatex pass 1", xelatex_run_1),
                summarize_process_output("bibtex", bibtex_run),
                summarize_process_output("xelatex pass 2", xelatex_run_2),
                summarize_process_output("xelatex pass 3", xelatex_run_3),
            ]
        )
        raise BuildError(
            f"PDF 渲染失败，未找到输出文件：{pdf_source}\n\n{compiler_logs}"
        )

    for label, result in (
        ("xelatex pass 1", xelatex_run_1),
        ("bibtex", bibtex_run),
        ("xelatex pass 2", xelatex_run_2),
        ("xelatex pass 3", xelatex_run_3),
    ):
        if result.returncode != 0:
            print(f"Warning: {label} exit={result.returncode}", file=sys.stderr)

    shutil.copy2(pdf_source, project_dir / f"{tex_stem}.pdf")
    clean_root_artifacts(project_dir, tex_stem)
    print(f"✓ PDF generated: {project_dir / f'{tex_stem}.pdf'}")
    print(f"✓ Build cache: {cache_dir}")
    synctex_path = cache_dir / f"{tex_stem}.synctex.gz"
    if synctex_path.exists():
        print(f"✓ SyncTeX: {synctex_path}")


def clean_project(project_dir: Path, tex_file: str, remove_pdf: bool) -> None:
    tex_path = resolve_tex_file(project_dir, tex_file)
    tex_stem = tex_path.stem
    clean_root_artifacts(project_dir, tex_stem)
    cache_dir = project_dir / CACHE_DIRNAME
    if cache_dir.exists():
        shutil.rmtree(cache_dir)
    if remove_pdf:
        pdf_path = project_dir / f"{tex_stem}.pdf"
        if pdf_path.exists():
            pdf_path.unlink()
    print(f"✓ Cleaned: {project_dir}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="NSFC 项目统一 TeX→PDF 渲染工具")
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="渲染 PDF")
    build_parser.add_argument(
        "--project-dir",
        type=Path,
        default=None,
        help="项目目录；默认自动向上定位包含 main.tex 与 extraTex/@config.tex 的目录。",
    )
    build_parser.add_argument(
        "--tex-file",
        default="main.tex",
        help="主 TeX 文件名，默认 main.tex。",
    )

    clean_parser = subparsers.add_parser("clean", help="清理缓存与根目录中间文件")
    clean_parser.add_argument(
        "--project-dir",
        type=Path,
        default=None,
        help="项目目录；默认自动向上定位。",
    )
    clean_parser.add_argument(
        "--tex-file",
        default="main.tex",
        help="主 TeX 文件名，默认 main.tex。",
    )
    clean_parser.add_argument(
        "--remove-pdf",
        action="store_true",
        help="清理时一并删除根目录 PDF。",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()
    project_dir = resolve_project_dir(getattr(args, "project_dir", None))

    if args.command == "build":
        build_project(project_dir, args.tex_file)
        return

    if args.command == "clean":
        clean_project(project_dir, args.tex_file, args.remove_pdf)
        return

    raise ValueError(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    main()
