#!/usr/bin/env python3
"""
pack_release.py - 打包 projects/ 下各子项目为 Release Assets

用法：
  python scripts/pack_release.py --tag v3.3.0          # 仅打包
  python scripts/pack_release.py --tag v3.3.0 --upload # 打包并上传到 GitHub Release

打包规范：
  - 输出目录：./tests/release-{tag}/（如 ./tests/release-v3.3.0/）
  - 每个子项目默认生成两类 zip：
      1. 普通包：{项目名}-{tag}.zip
      2. Overleaf 包：{项目名}-Overleaf-{tag}.zip
  - 普通包保留：
      1. PROJECT_INCLUDE_ITEMS 白名单中的文件/目录
      2. 项目根目录下的 *.code-workspace 文件
  - Overleaf 包会按项目类型自动内嵌对应公共包运行时文件：
      1. NSFC 项目：补入 bensz-nsfc 运行时文件与 bensz-nsfc-runtime.def
      2. SCI 项目：补入 bensz-paper 运行时文件
      3. Thesis 项目：补入 bensz-thesis 运行时文件
      4. CV 项目：补入 bensz-cv 运行时文件
  - 不存在的白名单项自动跳过（如 .vscode/ 不存在时不报错）
  - 不修改 projects/ 目录内任何文件
  - zip 生成操作仅在 tests/ 目录进行
"""

import argparse
import subprocess
import sys
import zipfile
from pathlib import Path

# zip 内保留的项目文件/目录（与 README / AGENTS.md 保持一致）
PROJECT_INCLUDE_ITEMS = [
    ".vscode",
    "artifacts",
    "assets",
    "bibtex-style",
    "code",
    "extraTex",
    "figures",
    "references",
    "scripts",
    "template",
    "main.docx",
    "main.pdf",
    "main.tex",
    "main-zh.pdf",
    "main-en.pdf",
    "main-zh.tex",
    "main-en.tex",
    "README.md",
]
REPO_ROOT = Path(__file__).parent.parent
PROJECTS_DIR = REPO_ROOT / "projects"
NSFC_PACKAGE_DIR = REPO_ROOT / "packages" / "bensz-nsfc"
PAPER_PACKAGE_DIR = REPO_ROOT / "packages" / "bensz-paper"
THESIS_PACKAGE_DIR = REPO_ROOT / "packages" / "bensz-thesis"
CV_PACKAGE_DIR = REPO_ROOT / "packages" / "bensz-cv"
TESTS_DIR = REPO_ROOT / "tests"
NSFC_PACKAGE_RUNTIME_ITEMS = [
    "bensz-nsfc-common.sty",
    "bensz-nsfc-core.sty",
    "bensz-nsfc-layout.sty",
    "bensz-nsfc-typography.sty",
    "bensz-nsfc-headings.sty",
    "bensz-nsfc-bibliography.sty",
    "profiles",
    "impl",
    "assets",
]
PAPER_PACKAGE_RUNTIME_ITEMS = [
    "bensz-paper.sty",
    "benszmanuscriptlatex.sty",
    "bml-core.sty",
    "bml-layout.sty",
    "bml-headings.sty",
    "bml-typography.sty",
    "bml-floats.sty",
    "bml-bibliography.sty",
    "bml-review.sty",
    "profiles",
]
THESIS_PACKAGE_RUNTIME_ITEMS = [
    "bensz-thesis.sty",
    "bthesis-core.sty",
    "profiles",
    "styles",
]
CV_PACKAGE_RUNTIME_ITEMS = [
    "bensz-cv.cls",
    "resume.cls",
    "fontawesome.sty",
    "fontawesomesymbols-generic.tex",
    "fontawesomesymbols-pdftex.tex",
    "fontawesomesymbols-xeluatex.tex",
    "linespacing_fix.sty",
    "zh_CN-Adobefonts_external.sty",
    "zh_CN-Adobefonts_internal.sty",
    "NotoSansSC_external.sty",
    "NotoSerifCJKsc_external.sty",
    "fonts",
    "profiles",
]
SKIP_FILE_NAMES = {".DS_Store", "Thumbs.db"}
SKIP_FILE_SUFFIXES = {".pyc", ".pyo"}
SKIP_DIR_NAMES = {"__pycache__", ".latex-cache", ".pytest_cache", ".mypy_cache", ".ruff_cache"}


def should_skip_path(path: Path) -> bool:
    if path.name in SKIP_FILE_NAMES:
        return True
    if path.suffix in SKIP_FILE_SUFFIXES:
        return True
    return any(part in SKIP_DIR_NAMES for part in path.parts)


def iter_tree_files(root: Path):
    for file in sorted(root.rglob("*")):
        if file.is_file() and not should_skip_path(file):
            yield file


def add_project_contents(zf: zipfile.ZipFile, project_dir: Path) -> None:
    for item_name in PROJECT_INCLUDE_ITEMS:
        item_path = project_dir / item_name
        if not item_path.exists():
            continue
        if item_path.is_file():
            if not should_skip_path(item_path):
                zf.write(item_path, arcname=item_name)
            continue
        for file in iter_tree_files(item_path):
            zf.write(file, arcname=file.relative_to(project_dir))

    for workspace_file in sorted(project_dir.glob("*.code-workspace")):
        if not should_skip_path(workspace_file):
            zf.write(workspace_file, arcname=workspace_file.name)


def detect_project_kind(project_dir: Path) -> str:
    if (project_dir / "references" / "meta.yaml").exists():
        return "paper"
    if project_dir.name.startswith("cv-"):
        return "cv"
    if project_dir.name.startswith("thesis-"):
        return "thesis"
    if (project_dir / "extraTex" / "@config.tex").exists() and project_dir.name.startswith("NSFC_"):
        return "nsfc"
    return "generic"


def build_overleaf_runtime_def() -> str:
    return "\n".join(
        [
            "% Auto-generated by scripts/pack_release.py for Overleaf release bundles.",
            r"\renewcommand{\NSFCPackageRootDir}{./}",
            r"\renewcommand{\NSFCAssetsDir}{assets/}",
            r"\renewcommand{\NSFCAssetFontsDir}{assets/fonts/}",
            r"\renewcommand{\NSFCAssetBibStyleBase}{assets/bibtex-style/gbt7714-nsfc}",
            "",
        ]
    )


def add_nsfc_runtime_bundle(zf: zipfile.ZipFile) -> None:
    for item_name in NSFC_PACKAGE_RUNTIME_ITEMS:
        item_path = NSFC_PACKAGE_DIR / item_name
        if not item_path.exists():
            raise FileNotFoundError(f"缺少 Overleaf 打包所需文件：{item_path}")
        if item_path.is_file():
            zf.write(item_path, arcname=item_name)
            continue
        for file in iter_tree_files(item_path):
            zf.write(file, arcname=file.relative_to(NSFC_PACKAGE_DIR))

    zf.writestr("bensz-nsfc-runtime.def", build_overleaf_runtime_def())


def add_paper_runtime_bundle(zf: zipfile.ZipFile) -> None:
    for item_name in PAPER_PACKAGE_RUNTIME_ITEMS:
        item_path = PAPER_PACKAGE_DIR / item_name
        if not item_path.exists():
            raise FileNotFoundError(f"缺少 Overleaf 打包所需文件：{item_path}")
        if item_path.is_file():
            zf.write(item_path, arcname=item_name)
            continue
        for file in iter_tree_files(item_path):
            zf.write(file, arcname=file.relative_to(PAPER_PACKAGE_DIR))


def add_thesis_runtime_bundle(zf: zipfile.ZipFile) -> None:
    for item_name in THESIS_PACKAGE_RUNTIME_ITEMS:
        item_path = THESIS_PACKAGE_DIR / item_name
        if not item_path.exists():
            raise FileNotFoundError(f"缺少 Overleaf 打包所需文件：{item_path}")
        if item_path.is_file():
            zf.write(item_path, arcname=item_name)
            continue
        for file in iter_tree_files(item_path):
            zf.write(file, arcname=file.relative_to(THESIS_PACKAGE_DIR))


def add_cv_runtime_bundle(zf: zipfile.ZipFile) -> None:
    for item_name in CV_PACKAGE_RUNTIME_ITEMS:
        item_path = CV_PACKAGE_DIR / item_name
        if not item_path.exists():
            raise FileNotFoundError(f"缺少 Overleaf 打包所需文件：{item_path}")
        if item_path.is_file():
            zf.write(item_path, arcname=item_name)
            continue
        for file in iter_tree_files(item_path):
            zf.write(file, arcname=file.relative_to(CV_PACKAGE_DIR))


def get_git_tag() -> str:
    """从 git 获取最新 tag。"""
    result = subprocess.run(
        ["git", "describe", "--tags", "--abbrev=0"],
        capture_output=True, text=True, cwd=REPO_ROOT
    )
    if result.returncode != 0:
        sys.exit("错误：无法自动获取 git tag，请通过 --tag 手动指定。")
    return result.stdout.strip()


def pack_project(project_dir: Path, output_dir: Path, tag: str) -> Path:
    """将单个子项目打包为普通 zip，返回 zip 路径。"""
    zip_name = f"{project_dir.name}-{tag}.zip"
    zip_path = output_dir / zip_name

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        add_project_contents(zf, project_dir)

    return zip_path


def pack_project_overleaf(project_dir: Path, output_dir: Path, tag: str) -> Path:
    """将单个子项目打包为可直接上传 Overleaf 的 zip，返回 zip 路径。"""
    zip_name = f"{project_dir.name}-Overleaf-{tag}.zip"
    zip_path = output_dir / zip_name

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        add_project_contents(zf, project_dir)
        project_kind = detect_project_kind(project_dir)
        if project_kind == "nsfc":
            add_nsfc_runtime_bundle(zf)
        elif project_kind == "paper":
            add_paper_runtime_bundle(zf)
        elif project_kind == "thesis":
            add_thesis_runtime_bundle(zf)
        elif project_kind == "cv":
            add_cv_runtime_bundle(zf)

    return zip_path


def upload_asset(tag: str, zip_path: Path) -> None:
    """通过 gh CLI 上传 zip 到 GitHub Release。"""
    result = subprocess.run(
        ["gh", "release", "upload", tag, str(zip_path), "--clobber"],
        cwd=REPO_ROOT
    )
    if result.returncode != 0:
        sys.exit(f"错误：上传 {zip_path.name} 失败。")


def main() -> None:
    parser = argparse.ArgumentParser(description="打包 Release Assets")
    parser.add_argument("--tag", help="版本 tag（如 v3.3.0），省略则自动从 git 获取")
    parser.add_argument("--upload", action="store_true", help="打包后上传到 GitHub Release")
    args = parser.parse_args()

    tag = args.tag or get_git_tag()
    output_dir = TESTS_DIR / f"release-{tag}"
    output_dir.mkdir(parents=True, exist_ok=True)

    if not NSFC_PACKAGE_DIR.exists():
        sys.exit(f"错误：未找到 NSFC 公共包目录 {NSFC_PACKAGE_DIR}")
    if not PAPER_PACKAGE_DIR.exists():
        sys.exit(f"错误：未找到 SCI 公共包目录 {PAPER_PACKAGE_DIR}")
    if not THESIS_PACKAGE_DIR.exists():
        sys.exit(f"错误：未找到 Thesis 公共包目录 {THESIS_PACKAGE_DIR}")
    if not CV_PACKAGE_DIR.exists():
        sys.exit(f"错误：未找到 CV 公共包目录 {CV_PACKAGE_DIR}")

    projects = sorted(p for p in PROJECTS_DIR.iterdir() if p.is_dir())
    if not projects:
        sys.exit(f"错误：{PROJECTS_DIR} 下没有找到子项目。")

    print(f"Tag: {tag}  |  输出目录: {output_dir.relative_to(REPO_ROOT)}")
    print("-" * 50)

    zips = []
    for project in projects:
        standard_zip = pack_project(project, output_dir, tag)
        standard_size_kb = standard_zip.stat().st_size // 1024
        print(f"  ✓ {standard_zip.name}  ({standard_size_kb} KB)")
        zips.append(standard_zip)

        overleaf_zip = pack_project_overleaf(project, output_dir, tag)
        overleaf_size_kb = overleaf_zip.stat().st_size // 1024
        print(f"  ✓ {overleaf_zip.name}  ({overleaf_size_kb} KB)")
        zips.append(overleaf_zip)

    if args.upload:
        print("\n上传到 GitHub Release...")
        for zip_path in zips:
            upload_asset(tag, zip_path)
            print(f"  ↑ {zip_path.name}")

    print(f"\n完成：{len(zips)} 个 zip 已生成。")


if __name__ == "__main__":
    main()
